# Generated by Django 5.0.3 on 2024-04-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(choices=[('Brownsville', 'Brownsville'), ('McAllen', 'McAllen'), ('Edinburg', 'Edinburg'), ('Harlingen', 'Harlingen'), ('Mission', 'Mission'), ('Pharr', 'Pharr'), ('Weslaco', 'Weslaco'), ('San Benito', 'San Benito'), ('Mercedes', 'Mercedes'), ('Alamo', 'Alamo')], max_length=300)),
                ('postal', models.IntegerField()),
                ('service', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Cleaning', 'Cleaning'), ('Electrical', 'Electrical'), ('AC', 'AC'), ('Landscaping', 'Landscaping'), ('Pest Control', 'Pest Control'), ('Roofing', 'Roofing'), ('Painting', 'Painting'), ('Carpeting', 'Carpeting')], max_length=20)),
                ('service_date', models.DateTimeField()),
                ('Commentary', models.TextField(max_length=300)),
            ],
        ),
    ]
